import streamlit as st
import pandas as pd
import ast
from datetime import datetime, timedelta
from fpdf import FPDF
import os
import gspread
from google.oauth2.service_account import Credentials
import io

# =========================================================
# 1. KONFIGURASI UTAMA & DATA KANTOR
# =========================================================
MARKETING_NAME  = "Asin"
MARKETING_WA    = "0815-8199-775"
MARKETING_EMAIL = "alattulis.tts@gmail.com"

COMPANY_NAME    = "PT. THEA THEO STATIONARY"
SLOGAN          = "Office & School Supplies Solution"
ADDR            = "Komp. Ruko Modernland Cipondoh Blok. AR No. 27, Tangerang"
OFFICE_PHONE    = "(021) 55780659"

# Password Admin
if "ADMIN_PASSWORD" in st.secrets:
    ADMIN_PASSWORD = st.secrets["ADMIN_PASSWORD"]
else:
    ADMIN_PASSWORD = "admin" 

# Warna Tema Luxury (Navy & Gold)
COLOR_NAVY = (0, 40, 85)
COLOR_GOLD = (184, 134, 11)
COLOR_TEXT = (30, 30, 30)

st.set_page_config(page_title=f"{COMPANY_NAME} - {MARKETING_NAME}", layout="wide")

# =========================================================
# 2. FUNGSI KONEKSI & DATABASE
# =========================================================
def get_creds():
    scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
    return Credentials.from_service_account_info(st.secrets["gcp_service_account"], scopes=scope)

def connect_gsheet():
    try:
        client = gspread.authorize(get_creds())
        sheet = client.open("Antrean Penawaran TTS").sheet1
        # --- AUTO HEADER FIX (Anti-Error Waktu) ---
        if not sheet.get_all_values():
            header = ["Waktu", "Customer", "UP", "WA", "Pesanan", "Status", "Sales"]
            sheet.append_row(header)
        return sheet
    except Exception as e:
        st.error(f"Koneksi GSheets Gagal: {e}")
        return None

def load_db():
    if os.path.exists("database_barang.xlsx"):
        try:
            df = pd.read_excel("database_barang.xlsx")
            df.columns = df.columns.str.strip()
            if 'Harga' in df.columns:
                df['Harga'] = pd.to_numeric(df['Harga'], errors='coerce').fillna(0)
            return df
        except: pass
    return pd.DataFrame(columns=['Nama Barang', 'Harga', 'Satuan'])

df_barang = load_db()

# =========================================================
# 3. PDF ENGINE (PRESIDENTIAL SUITE - MULTIPAGE BULLETPROOF)
# =========================================================
class PenawaranPDF(FPDF):
    def header(self):
        # 1. BACKGROUND HEADER (NAVY)
        self.set_fill_color(*COLOR_NAVY)
        self.rect(0, 0, 210, 55, 'F') # Ditambah sedikit tingginya

        # 2. WHITE CANVAS (AREA LOGO)
        self.set_fill_color(255, 255, 255)
        self.rect(10, 0, 50, 55, 'F') 

        # 3. TIANG EMAS
        self.set_fill_color(*COLOR_GOLD)
        self.rect(60, 0, 2, 55, 'F') 
        self.rect(64, 0, 0.5, 55, 'F') 

        # 4. LOGO
        if os.path.exists("logo.png"):
            self.image("logo.png", 15, 12, 40) 

        # 5. TYPOGRAPHY
        self.set_y(12); self.set_x(72)
        self.set_font('Arial', 'B', 20); self.set_text_color(255, 255, 255)
        self.cell(0, 8, COMPANY_NAME, ln=1)
        
        self.set_x(72); self.set_font('Arial', 'B', 10); self.set_text_color(184, 134, 11)
        self.cell(0, 6, "  ".join(SLOGAN.upper()), ln=1)
        
        # Garis putih bawah slogan
        self.set_fill_color(255, 255, 255); self.rect(72, 28, 120, 0.2, 'F')

        # Info Kontak
        self.set_y(32); self.set_x(72)
        self.set_font('Arial', '', 8); self.set_text_color(220, 220, 220)
        self.cell(0, 4, ADDR, ln=1)
        
        self.set_x(72)
        self.cell(0, 4, f"Office: {OFFICE_PHONE}  |  WA: {MARKETING_WA}", ln=1)
        
        self.set_x(72)
        self.cell(0, 4, f"Email: {MARKETING_EMAIL}", ln=1)

        # --- KUNCI POSISI AKHIR HEADER ---
        self.set_y(65) # Memastikan body dimulai dari koordinat 65

    def footer(self):
        self.set_y(-25)
        self.set_fill_color(*COLOR_NAVY); self.rect(0, 272, 210, 25, 'F')
        self.set_fill_color(*COLOR_GOLD); self.rect(0, 292, 210, 5, 'F') 
        self.set_y(-18)
        self.set_font('Arial', 'B', 9); self.set_text_color(255, 255, 255)
        self.cell(0, 5, "THANK YOU FOR YOUR BUSINESS", 0, 1, 'C')
        self.set_font('Arial', '', 7); self.set_text_color(184, 134, 11) 
        self.cell(0, 4, f"Page {self.page_no()} | Generated by TTS System", 0, 0, 'C')

# Fungsi Pembantu Header Tabel (Agar bisa dipanggil berulang)
def draw_table_header(pdf):
    pdf.set_font('Arial', 'B', 9); pdf.set_text_color(255, 255, 255); pdf.set_fill_color(*COLOR_NAVY)
    pdf.cell(10, 10, 'NO', 0, 0, 'C', True)
    pdf.cell(90, 10, 'DESCRIPTION', 0, 0, 'L', True)
    pdf.cell(20, 10, 'QTY', 0, 0, 'C', True)
    pdf.cell(20, 10, 'UNIT', 0, 0, 'C', True)
    pdf.cell(25, 10, 'PRICE', 0, 0, 'R', True)
    pdf.cell(25, 10, 'TOTAL', 0, 1, 'R', True)

def generate_pdf(no_surat, nama_cust, pic, df_order, subtotal, ppn, grand_total):
    pdf = PenawaranPDF()
    # Kunci margin atas di 70 agar ada space kosong di bawah kop
    pdf.set_margins(left=10, top=70, right=10)
    pdf.set_auto_page_break(auto=True, margin=30)
    pdf.add_page()
    
    # --- HALAMAN 1: INFO PENERIMA ---
    pdf.set_y(70) 
    pdf.set_font('Arial', 'B', 24); pdf.set_text_color(*COLOR_NAVY)
    pdf.cell(0, 10, "QUOTATION", ln=1, align='R')
    pdf.set_font('Arial', '', 9); pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 5, f"Reference: {no_surat}", ln=1, align='R')
    
    waktu_skrg = datetime.utcnow() + timedelta(hours=7)
    pdf.cell(0, 5, f"Date: {waktu_skrg.strftime('%d %B %Y')}", ln=1, align='R')
    
    pdf.set_y(70) 
    pdf.set_font('Arial', 'B', 9); pdf.set_text_color(*COLOR_GOLD)
    pdf.cell(0, 5, "PREPARED FOR:", ln=1)
    pdf.set_font('Arial', 'B', 13); pdf.set_text_color(*COLOR_TEXT)
    pdf.cell(0, 7, str(nama_cust).upper(), ln=1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 5, f"Attention: {pic}", ln=1)
    
    pdf.ln(10)
    
    # --- TABEL BARANG ---
    draw_table_header(pdf)

    pdf.set_font('Arial', '', 9); pdf.set_text_color(*COLOR_TEXT)
    fill = False
    for i, row in df_order.iterrows():
        # CEK APAKAH BUTUH PINDAH HALAMAN (Jika sisa space < 20mm)
        if pdf.get_y() > 240:
            pdf.add_page()
            draw_table_header(pdf) # Cetak ulang header tabel di halaman baru
            pdf.set_font('Arial', '', 9); pdf.set_text_color(*COLOR_TEXT)

        pdf.set_fill_color(248, 249, 252) if fill else pdf.set_fill_color(255, 255, 255)
        pdf.cell(10, 8, str(i+1), 0, 0, 'C', True)
        pdf.cell(90, 8, f" {row['Nama Barang']}", 0, 0, 'L', True)
        pdf.cell(20, 8, str(int(row['Qty'])), 0, 0, 'C', True)
        pdf.cell(20, 8, str(row['Satuan']), 0, 0, 'C', True)
        pdf.cell(25, 8, f"{row['Harga']:,.0f} ", 0, 0, 'R', True)
        pdf.cell(25, 8, f"{row['Total_Row']:,.0f} ", 0, 1, 'R', True)
        
        # Garis Emas
        pdf.set_draw_color(184, 134, 11); pdf.set_line_width(0.1)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        fill = not fill

    # --- TOTAL & SIGNATURE ---
    # Cek lagi sebelum cetak total agar tidak terpotong footer
    if pdf.get_y() > 220: pdf.add_page()

    pdf.ln(5)
    pdf.set_x(130)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(45, 8, "Sub Total", 0, 0, 'L'); pdf.cell(25, 8, f" {subtotal:,.0f}", 0, 1, 'R')
    pdf.set_x(130)
    pdf.cell(45, 8, "VAT (PPN 11%)", 0, 0, 'L'); pdf.cell(25, 8, f" {ppn:,.0f}", 0, 1, 'R')
    pdf.set_x(130); pdf.set_fill_color(*COLOR_NAVY); pdf.set_text_color(255, 255, 255)
    pdf.cell(70, 10, f" TOTAL IDR {grand_total:,.0f} ", 0, 1, 'R', True)

    pdf.ln(10); pdf.set_font('Arial', 'B', 9); pdf.set_text_color(*COLOR_NAVY); pdf.cell(0, 5, "TERMS & CONDITIONS:", ln=1)
    pdf.set_font('Arial', '', 8); pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 4, "1. Prices are subject to change with notice.\n2. Validity: 14 Days from date of quotation.\n3. Delivery: Within 1 working day after PO confirmation.")

    pdf.ln(10); pdf.set_font('Arial', '', 10); pdf.set_text_color(*COLOR_TEXT)
    pdf.cell(130, 5, "", 0, 0); pdf.cell(60, 5, "Yours Faithfully,", 0, 1, 'C')
    pdf.ln(15) 
    pdf.set_font('Arial', 'B', 10); pdf.set_text_color(*COLOR_NAVY)
    pdf.cell(130, 5, "", 0, 0); pdf.cell(60, 5, MARKETING_NAME.upper(), 0, 1, 'C')
    pdf.set_font('Arial', '', 9); pdf.set_text_color(100, 100, 100)
    pdf.cell(130, 5, "", 0, 0); pdf.cell(60, 5, "Sales Consultant", 0, 1, 'C')
    
    return pdf.output(dest='S').encode('latin-1')
    
# =========================================================
# 4. UI UTAMA (STREAMLIT)
# =========================================================
st.sidebar.title(f"Portal {MARKETING_NAME}")
menu = st.sidebar.selectbox("Pilih Menu:", ["🏠 Home", "📝 Portal Customer", "👨‍💻 Admin Dashboard"])

if 'cart' not in st.session_state: st.session_state.cart = []

if menu == "🏠 Home":
    st.title(f"Selamat Datang di {COMPANY_NAME}")
    st.info(f"Marketing Aktif: {MARKETING_NAME} | {MARKETING_WA}")

elif menu == "📝 Portal Customer":
    st.subheader("Form Pengajuan Penawaran")
    with st.container(border=True):
        col1, col2 = st.columns(2)
        nama_toko = col1.text_input("🏢 Nama Perusahaan / Toko")
        up_nama = col2.text_input("👤 Nama Penerima (UP)")
        wa_nomor = col1.text_input("📞 Nomor WhatsApp Pembeli")
        picks = st.multiselect("📦 Pilih Barang:", options=df_barang['Nama Barang'].tolist())
        if st.button("Tambahkan ke Keranjang"):
            for p in picks:
                if p not in st.session_state.cart: st.session_state.cart.append(p)
            st.rerun()

    if st.session_state.cart:
        st.markdown("### 📋 Daftar Pesanan")
        list_pesanan = []
        for item in st.session_state.cart:
            row_b = df_barang[df_barang['Nama Barang'] == item].iloc[0]
            with st.container(border=True):
                c1, c2, c3, c4 = st.columns([3, 1.5, 1, 0.5])
                c1.markdown(f"**{item}**")
                c2.markdown(f"Rp {row_b['Harga']:,.0f} / {row_b['Satuan']}")
                qty = c3.number_input(f"Jumlah", min_value=1, value=1, key=f"q_c_{item}")
                if c4.button("❌", key=f"del_c_{item}"):
                    st.session_state.cart.remove(item); st.rerun()
                list_pesanan.append({"Nama Barang": str(item), "Qty": int(qty), "Harga": float(row_b['Harga']), "Satuan": str(row_b['Satuan']), "Total_Row": float(qty * row_b['Harga'])})

        if st.button(f"🚀 Kirim Pengajuan ke {MARKETING_NAME}", use_container_width=True):
            sheet = connect_gsheet()
            if sheet and nama_toko:
                wkt = (datetime.utcnow() + timedelta(hours=7)).strftime("%Y-%m-%d %H:%M")
                sheet.append_row([wkt, nama_toko, up_nama, wa_nomor, str(list_pesanan), "Pending", MARKETING_NAME])
                st.success("Terkirim! Terima kasih."); st.session_state.cart = []

elif menu == "👨‍💻 Admin Dashboard":
    st.title(f"Admin Dashboard - {MARKETING_NAME}")
    
    # --- FUNGSI BARU: GENERATE EXCEL ---
    def generate_excel(no_surat, nama_cust, pic, df_order, subtotal, ppn, grand_total):
        output = io.BytesIO()
        with pd.ExcelWriter(output, engine='xlsxwriter') as writer:
            # 1. Buat Header Info
            header_info = pd.DataFrame([
                [COMPANY_NAME, ""],
                [SLOGAN, ""],
                [ADDR, ""],
                ["", ""],
                ["QUOTATION", ""],
                ["Reference No:", no_surat],
                ["Date:", (datetime.utcnow() + timedelta(hours=7)).strftime('%d %B %Y')],
                ["Customer:", nama_cust.upper()],
                ["Attention:", pic],
                ["", ""]
            ])
            header_info.to_excel(writer, index=False, header=False, sheet_name='Quotation', startrow=0)

            # 2. Buat Tabel Barang
            export_df = df_order[['Nama Barang', 'Qty', 'Satuan', 'Harga', 'Total_Row']].copy()
            export_df.columns = ['DESCRIPTION', 'QTY', 'UNIT', 'UNIT PRICE', 'TOTAL AMOUNT']
            export_df.to_excel(writer, index=False, sheet_name='Quotation', startrow=11)

            # 3. Buat Summary Total
            start_row_total = 11 + len(export_df) + 1
            summary_df = pd.DataFrame([
                ["Sub Total", subtotal],
                ["PPN (11%)", ppn],
                ["GRAND TOTAL", grand_total]
            ])
            summary_df.to_excel(writer, index=False, header=False, sheet_name='Quotation', startrow=start_row_total, startcol=3)
            
        return output.getvalue()

    pwd = st.sidebar.text_input("Password:", type="password")
    if pwd == ADMIN_PASSWORD:
        sheet = connect_gsheet()
        if sheet:
            try:
                all_vals = sheet.get_all_values()
                if len(all_vals) > 1:
                    df_gs = pd.DataFrame(all_vals[1:], columns=all_vals[0])
                    pending = df_gs[(df_gs['Status'] == 'Pending') & (df_gs['Sales'] == MARKETING_NAME)]
                    
                    if not pending.empty:
                        for idx, row in pending.iterrows():
                            real_row_idx = df_gs.index[idx] + 2 
                            waktu_str = row.get('Waktu', 'Tanpa Tanggal')
                            
                            with st.expander(f"🛠️ KELOLA: {row['Customer']} ({waktu_str})", expanded=True):
                                items_list = ast.literal_eval(str(row['Pesanan']))
                                
                                with st.form(key=f"form_edit_{idx}"):
                                    st.write("### 1. Edit Barang, Harga & Posisi")
                                    st.info("💡 **Trik Cepat:** Ubah angka di kolom **Pos** untuk menyelipkan barang.")
                                    
                                    temp_items = []
                                    for i, r in enumerate(items_list):
                                        ca, cb, cc, cd, cp, ce = st.columns([2.5, 0.8, 1.2, 1.5, 0.8, 0.6])
                                        ca.markdown(f"**{r['Nama Barang']}**")
                                        
                                        safe_name = str(r['Nama Barang']).replace(" ", "_").replace(".", "")
                                        unique_key = f"{idx}_{i}_{safe_name}" 
                                        
                                        nq = cb.number_input("Qty", value=int(r['Qty']), key=f"q_{unique_key}")
                                        opsi_satuan = ["Pcs", "Roll", "Dus", "Pack", "Rim", "Box", "Lusin", "Unit", "Set", "Lembar", "Botol"]
                                        satuan_awal = r.get('Satuan', 'Pcs')
                                        if satuan_awal not in opsi_satuan: opsi_satuan.insert(0, satuan_awal)
                                        ns = cc.selectbox("Satuan", options=opsi_satuan, index=opsi_satuan.index(satuan_awal), key=f"s_{unique_key}")
                                        nh = cd.number_input("Harga/Unit", value=float(r['Harga']), key=f"h_{unique_key}")
                                        n_pos = cp.number_input("Pos", value=float(i+1), step=0.5, format="%.1f", key=f"p_{unique_key}")
                                        to_delete = ce.checkbox("Hapus", key=f"d_{unique_key}")
                                        
                                        temp_items.append({"delete": to_delete, "pos_index": n_pos, "Nama Barang": r['Nama Barang'], "Qty": nq, "Harga": nh, "Satuan": ns})
                                    
                                    st.divider()
                                    st.write("### 2. Tambah Barang Baru")
                                    new_items = st.multiselect("Cari Barang Tambahan:", options=df_barang['Nama Barang'].tolist(), key=f"add_{idx}")
                                    insert_pos = st.number_input("Masukan Barang Baru Ke Urutan:", value=float(len(items_list)+1), step=1.0, key=f"inspos_{idx}")
                                    
                                    st.divider()
                                    submitted = st.form_submit_button("💾 Simpan Perubahan & Urutan", use_container_width=True)
                                    
                                    if submitted:
                                        import time
                                        edited_items = []
                                        for item in temp_items:
                                            if not item["delete"]:
                                                item["Total_Row"] = item["Qty"] * item["Harga"]
                                                edited_items.append(item)
                                        for p in new_items:
                                            rb = df_barang[df_barang['Nama Barang'] == p].iloc[0]
                                            edited_items.append({"pos_index": insert_pos, "Nama Barang": p, "Qty": 1, "Harga": float(rb['Harga']), "Satuan": str(rb['Satuan']), "Total_Row": float(1 * rb['Harga'])})
                                            insert_pos += 0.1 
                                            
                                        edited_items = sorted(edited_items, key=lambda x: x["pos_index"])
                                        final_list = [{"Nama Barang": i["Nama Barang"], "Qty": i["Qty"], "Harga": i["Harga"], "Satuan": i["Satuan"], "Total_Row": i["Total_Row"]} for i in edited_items]
                                        sheet.update_cell(real_row_idx, 5, str(final_list))
                                        
                                        for k in list(st.session_state.keys()):
                                            if any(k.startswith(prefix + f"_{idx}_") for prefix in ["q", "h", "s", "p", "d"]) or k.startswith(f"add_{idx}") or k.startswith(f"inspos_{idx}"):
                                                del st.session_state[k]
                                        st.success("Tersimpan!")
                                        time.sleep(1.5)
                                        st.rerun()

                                # --- AREA DOWNLOAD (PDF & EXCEL) ---
                                final_df = pd.DataFrame(items_list) 
                                if not final_df.empty:
                                    subt = final_df['Total_Row'].sum(); tax = subt * 0.11; gtot = subt + tax
                                    c1, c2 = st.columns(2)
                                    no_s = c1.text_input("No Surat:", value=f"/S-TTS/III/{datetime.now().year}", key=f"no_{idx}")
                                    c2.metric("Total Quotation", f"Rp {gtot:,.0f}")
                                    
                                    # Kolom Tombol Download
                                    btn1, btn2 = st.columns(2)
                                    
                                    # PDF Download
                                    pdf_data = generate_pdf(no_s, row['Customer'], row['UP'], final_df, subt, tax, gtot)
                                    btn1.download_button("📩 Download PDF Presidential", data=pdf_data, file_name=f"TTS_{row['Customer']}.pdf", key=f"dl_pdf_{idx}", use_container_width=True)
                                    
                                    # EXCEL Download
                                    excel_data = generate_excel(no_s, row['Customer'], row['UP'], final_df, subt, tax, gtot)
                                    btn2.download_button("📊 Download Excel Quotation", data=excel_data, file_name=f"TTS_{row['Customer']}.xlsx", key=f"dl_xls_{idx}", use_container_width=True)
                                    
                                    st.divider()
                                    if st.button("✅ Selesai & Hapus dari Antrean", key=f"fin_{idx}", type="primary", use_container_width=True):
                                        sheet.update_cell(real_row_idx, 6, "Processed"); st.rerun()
                    else: st.info(f"Tidak ada antrean pending untuk {MARKETING_NAME}.")
            except Exception as e: st.error(f"Error detail: {e}")



